#:schema node_modules/wrangler/config-schema.json
name = "chittycharge"
main = "src/index.ts"
compatibility_date = "2025-10-11"
workers_dev = false
account_id = "0bc21e3a5a9de1a4cc843be9c3e98121"

# Single worker, environment-aware routing
[[kv_namespaces]]
binding = "HOLDS"
id = "a1685cca731f43c397db4e79b80ea075"

[[routes]]
pattern = "charge.chitty.cc/*"
zone_name = "chitty.cc"

[observability]
enabled = true

[vars]
ENVIRONMENT = "production"
CHITTYCONNECT_URL = "https://connect.chitty.cc"
CHITTYREGISTRY_URL = "https://registry.chitty.cc"
